name: Auto linter
on: 
  push:
    paths: "*.py"
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout/clone code
        uses: actions/checkout@v7
      - name: install linter
        run: pip install ruff
